export const ApiRouter = {
  LOCAL: process.env.REACT_APP_LOCAL_API_URL,
  GLOBOAL: process.env.REACT_APP_GLOBAL_API_URL,
  SOCKET_LOCAL: process.env.REACT_APP_LOCAL_SOCKET_API_URL,
  SOCKET_GLOBOAL: process.env.REACT_APP_GLOBAL_SOCKET_API_URL,
};
