export const FriendsApi = {
  ADD_FRIEND: '/friends/add-friends',
  GET_LIST_FRIEND: '/friends/get-list-friends',
  ACCEPT_FRIENDS: '/friends/accept-friends',
  DECLINE_FRIENDS: '/friends/decline-friends',
};

export const REPONSE_CONSTANT = {
  ADD_FRIEND_SUCCESS: 'ADD_FRIEND_SUCCESS',
  ADD_FRIEND_FAIL: 'ADD_FRIEND_FAIL',
  GET_LIST_FRIEND_SUCCESS: 'GET_LIST_FRIEND_SUCCESS',
  GET_LIST_FRIEND_FAIL: 'GET_LIST_FRIEND_FAIL',
  ACCEPT_FRIENDS_SUCCESS: 'ACCEPT_FRIENDS_SUCCESS',
  ACCEPT_FRIENDS_FAIL: 'ACCEPT_FRIENDS_FAIL',
  DECLINE_FRIENDS_SUCCESS: 'DECLINE_FRIENDS_SUCCESS',
  DECLINE_FRIENDS_FAIL: 'DECLINE_FRIENDS_FAIL',
};
