export const AuthApi = {
  SIGN_IN: '/signIn',
  SIGN_UP: '/signUp',
  GET_USER_BY_ID: '/getUserById/',
  CHANGE_STATUS_IS_ONLINE: '/changeStatusOnline',
};

export const REPONSE_CONSTANT = {
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAIL: 'SIGN_IN_FAIL',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAIL: 'SIGN_UP_FAIL',
  GET_USER_BY_ID_SUCCESS: 'GET_USER_BY_ID_SUCCESS',
  GET_USER_BY_ID_FAIL: 'GET_USER_BY_ID_FAIL',
  CHANGE_STATUS_IS_ONLINE_SUCCESS: 'CHANGE_STATUS_IS_ONLINE_SUCCESS',
  CHANGE_STATUS_IS_ONLINE_FAIL: 'CHANGE_STATUS_IS_ONLINE_FAIL',
};

export const REPONSE_MESSAGE = {
  SIGN_IN_SUCCESS: 'Đăng nhập thành công',
  SIGN_IN_FAIL: 'Đăng nhập thất bại',
  SIGN_UP_SUCCESS: 'Đăng ký thành công',
  SIGN_UP_FAIL: 'Đăng ký thất bại',
};

export const JOIN_ROOM = 'JOIN_ROOM';
