export const ChatAppApi = {
  LIST_USER: '/listUser',
  CONVERT_STATION_MY_FRIEND: '/convertStationMyFriend/',
  NEW_MESSAGE: '/newMessage',

  GET_USER_BY_ID: '/userById/',
  GET_FRIEND_BY_ID: '/friendById/',
  LIST_MESSAGE: '/listMessage',
  SAVE_CONVERT_STATION: '/saveConvertStation',
  CONVERT_STATION_BY_USER_ID: '/convertStationByUserId',
  FIRST_USER_ID: '/firstUserId=?',
  SECONDARY_USER_ID: '/secondaryUserId=?',
};

export const REPONSE_CONSTANT = {
  LIST_USER_SUCCESS: 'LIST_USER_SUCCESS',
  LIST_USER_FAIL: 'LIST_USER_FAIL',
  GET_USER_BY_ID_SUCCESS: 'GET_USER_BY_ID_SUCCESS',
  GET_USER_BY_ID_FAIL: 'GET_USER_BY_ID_FAIL',
  LIST_MESSAGE_SUCCESS: 'LIST_MESSAGE_SUCCESS',
  LIST_MESSAGE_FAIL: 'LIST_MESSAGE_FAIL',
  NEW_MESSAGE_SUCCESS: 'NEW_MESSAGE_SUCCESS',
  NEW_MESSAGE_FAIL: 'NEW_MESSAGE_FAIL',
  CONVERT_STATION_MY_FRIEND_SUCCESS: 'CONVERT_STATION_MY_FRIEND_SUCCESS',
  CONVERT_STATION_MY_FRIEND_FAIL: 'CONVERT_STATION_MY_FRIEND_FAIL',
  SAVE_CONVERT_STATION_SUCCESS: 'SAVE_CONVERT_STATION_SUCCESS',
  SAVE_CONVERT_STATION_FAIL: 'SAVE_CONVERT_STATION_FAIL',
  CONVERT_STATION_BY_USER_ID_SUCCESS: 'CONVERT_STATION_BY_USER_ID_SUCCESS',
  CONVERT_STATION_BY_USER_ID_FAIL: 'CONVERT_STATION_BY_USER_ID_FAIL',
  FIND_TWO_USER_BY_ID_SUCCESS: 'FIND_TWO_USER_BY_ID_SUCCESS',
  FIND_TWO_USER_BY_ID_FAIL: 'FIND_TWO_USER_BY_ID_FAIL',
};

export const REPONSE_MESSAGE = {
  LIST_USER_SUCCESS: 'Lấy danh sách thành công',
  LIST_USER_FAIL: 'Lấy danh sách thất bại',
  LIST_MESSAGE_SUCCESS: 'Lấy danh sách thành công',
  LIST_MESSAGE_FAIL: 'Lấy danh sách thất bại',
};
