export const ChatAppApi = {
  LIST_USER: '/listUser',
  SAVE_CONVERT_STATION: '/saveConvertStation',
  GET_LIST_MESSAGE: '/getListMessages',
  NEW_MESSAGE: '/newMessage',
  CHANGE_STATUS_ONLINE: '/changeStatusOnline',
  CHANGE_STATUS_OFFLINE: '/changeStatusoffline',
};

export const REPONSE_CONSTANT = {
  LIST_USER_SUCCESS: 'LIST_USER_SUCCESS',
  LIST_USER_FAIL: 'LIST_USER_FAIL',
  SAVE_CONVERT_STATION_SUCCESS: 'SAVE_CONVERT_STATION_SUCCESS',
  SAVE_CONVERT_STATION_FAIL: 'SAVE_CONVERT_STATION_FAIL',
  GET_LIST_MESSAGE_SUCCESS: 'GET_LIST_MESSAGE_SUCCESS',
  GET_LIST_MESSAGE_FAIL: 'GET_LIST_MESSAGE_FAIL',
  NEW_MESSAGE_SUCCESS: 'NEW_MESSAGE_SUCCESS',
  NEW_MESSAGE_FAIL: 'NEW_MESSAGE_FAIL',
  CHANGE_STATUS_ONLINE_SUCCESS: 'CHANGE_STATUS_ONLINE_SUCCESS',
  CHANGE_STATUS_ONLINE_FAIL: 'CHANGE_STATUS_ONLINE_FAIL',
  CHANGE_STATUS_OFFLINE_SUCCESS: 'CHANGE_STATUS_OFFLINE_SUCCESS',
  CHANGE_STATUS_OFFLINE_FAIL: 'CHANGE_STATUS_OFFLINE_FAIL',
};

export const REPONSE_MESSAGE = {
  LIST_USER_SUCCESS: 'Lấy danh sách thành công',
  LIST_USER_FAIL: 'Lấy danh sách thất bại',
  LIST_MESSAGE_SUCCESS: 'Lấy danh sách thành công',
  LIST_MESSAGE_FAIL: 'Lấy danh sách thất bại',
};
